import { TRIDENT_CONFIG } from '../config.js';

export function generateBuildSpecArtifact(
  targetPath: string,
  projectName: string,
  requirements: string,
  architecture: string
): string {
  const ts = new Date().toISOString();
  const safeName = projectName.replace(/[^a-zA-Z0-9_-]/g, '-');

  let a = `# BUILD SPEC — ${projectName}\n\n`;
  a += `**Target:** ${targetPath}\n`;
  a += `**Generated:** ${ts}\n`;
  a += `**Status:** PLANNING\n\n`;

  a += `## Requirements\n\n`;
  a += `${requirements}\n\n`;

  a += `## Architecture Overview\n\n`;
  a += `\`\`\`\n${architecture}\n\`\`\`\n\n`;

  a += `## File Layout\n\n`;
  a += `\`\`\`\n`;
  a += `src/\n`;
  a += `  index.ts              — Plugin entry (default export)\n`;
  a += `  orchestrator.ts       — State machine, mode management\n`;
  a += `  hooks/\n`;
  a += `    ${safeName}-hooks.ts — 4 hooks (chat.message, tool.before/after, system.transform)\n`;
  a += `  tools/\n`;
  a += `    ${safeName}-tools.ts — Tool definitions with zod schemas\n`;
  a += `  agents/\n`;
  a += `    definitions.ts      — Agent config (name, color, mode)\n`;
  a += `  audit-engine/         — Audit layers (if applicable)\n`;
  a += `\`\`\`\n\n`;

  a += `## Build Chain\n\n`;
  a += `| Step | Command | Purpose |\n`;
  a += `|------|---------|----------|\n`;
  a += `| 1 | \`tsc --noEmit\` | Type checking |\n`;
  a += `| 2 | \`esbuild src/index.ts --bundle --platform=node --format=esm --outfile=dist/index.js --sourcemap --target=node20\` | Single-file bundle |\n`;
  a += `| 3 | \`node -e "require('./dist/index.js')"\` | Load verification |\n`;
  a += `\n`;

  a += `## Hook Wiring\n\n`;
  a += `| Hook | Purpose | Input Shape | Output Mutation |\n`;
  a += `|------|---------|-------------|----------------|\n`;
  a += `| \`chat.message\` | Session tracking, intent detection | \`{agent, sessionID, message}\` | None (side effects only) |\n`;
  a += `| \`tool.execute.before\` | Pre-tool audit trail | \`{tool, sessionID, callID}\` | \`output.args\` modification |\n`;
  a += `| \`tool.execute.after\` | Post-tool verification | \`{tool, sessionID}\` | None (logging) |\n`;
  a += `| \`experimental.chat.system.transform\` | Identity injection | \`{agent, name}\` | \`output.system.push()\` |\n`;
  a += `\n`;

  a += `## Tool Registration\n\n`;
  a += `| Tool | Zod Schema | Description |\n`;
  a += `|------|------------|-------------|\n`;
  a += `| \`${safeName}-status\` | \`{}\` | Show current state |\n`;
  a += `| \`${safeName}-audit\` | \`{targetPath: z.string(), action: z.enum(['full','quick'])}\` | Run audit |\n`;
  a += `| \`${safeName}-help\` | \`{}\` | Show commands |\n`;
  a += `\n`;

  a += `## Agent Config\n\n`;
  a += `\`\`\`json\n`;
  a += `{\n`;
  a += `  "${safeName}": {\n`;
  a += `    "model": "deepseek/deepseek-v4-flash",\n`;
  a += `    "system": "You are ${projectName}. Use ${safeName}-audit to audit code.",\n`;
  a += `    "color": "#8B5CF6",\n`;
  a += `    "mode": "primary"\n`;
  a += `  }\n`;
  a += `}\n`;
  a += `\`\`\`\n\n`;

  a += `## Container Test Plan\n\n`;
  a += `\`\`\`bash\n`;
  a += `docker run -d --name test-${safeName} \\\n`;
  a += `  -e DEEPSEEK_API_KEY=$KEY \\\n`;
  a += `  -v "$SNAP:/workspace:ro" \\\n`;
  a += `  -v "dist/index.js:/root/.config/opencode/plugins/${safeName}/dist/index.js:ro" \\\n`;
  a += `  --entrypoint "" ${TRIDENT_CONFIG.containerImage} sleep 3600\n`;
  a += `\`\`\`\n\n`;

  a += `## Ship Gate\n\n`;
  a += `- [ ] \`tsc --noEmit\` — 0 errors\n`;
  a += `- [ ] \`esbuild --bundle\` — single file, no relative imports\n`;
  a += `- [ ] Node.js load — hooks + tools present\n`;
  a += `- [ ] Container TUI — identity injection works\n`;
  a += `- [ ] Container TUI — all tools registered and functional\n`;
  a += `- [ ] Self-audit score >= 90/100\n`;

  a += `\n---\n*Generated by Trident v4.3 Deep Planning Engine*\n`;
  return a;
}

export function generateContextLibraryManifest(
  projectName: string,
  architecture: string,
  patterns: string[],
  failures: string[],
  decisions: string[]
): string {
  let a = `# CONTEXT LIBRARY MANIFEST — ${projectName}\n\n`;
  a += `This manifest defines all files in the context-library/ folder.\n`;
  a += `Each file should be dense, reference-grade, no filler.\n\n`;

  a += `## File Structure\n\n`;
  a += `| File | Content Source | Description |\n`;
  a += `|------|---------------|-------------|\n`;
  a += `| \`00_INDEX.md\` | Generated | Purpose, file listing, key principles, design decisions table |\n`;
  a += `| \`01_ARCHITECTURE.md\` | architecture param | Complete system architecture with ASCII diagrams, data flow, component map |\n`;
  a += `| \`02_PATTERNS.md\` | patterns[] param | All patterns: name, description, code example, when to use, anti-pattern |\n`;
  a += `| \`03_FAILURES.md\` | failures[] param | All failure modes: symptom, root cause, fix, prevention |\n`;
  a += `| \`04_DECISIONS.md\` | decisions[] param | All design decisions: decision, choice, rationale, alternatives rejected |\n`;
  a += `| \`05_BUILD_PLAN.md\` | Generated | Phase-by-phase build workflow with exact commands |\n`;
  a += `| \`06_HOOK_API.md\` | Generated | Hook contracts: input/output shapes, code examples, anti-patterns |\n`;
  a += `| \`07_CONTAINER_TESTING.md\` | Generated | Container test protocol: image, binary, T2 steps, evidence collection |\n`;
  a += `| \`08_SUCCESS_CRITERIA.md\` | Generated | Ship gate requirements: must-pass checks, score thresholds |\n`;
  a += `\n`;

  a += `## Content Sources\n\n`;
  a += `### Patterns (${patterns.length})\n`;
  for (const p of patterns) { a += `- ${p}\n`; }
  a += `\n### Failures (${failures.length})\n`;
  for (const f of failures) { a += `- ${f}\n`; }
  a += `\n### Decisions (${decisions.length})\n`;
  for (const d of decisions) { a += `- ${d}\n`; }

  a += `\n---\n*Generated by Trident v4.3 Deep Planning Engine*\n`;
  return a;
}
