import * as os from 'os';
import * as path from 'path';
import { TRIDENT_CONFIG } from '../config.js';

interface ProviderConfig {
  npm?: string;
  options?: {
    baseURL?: string;
    apiKey?: string;
    [key: string]: string | undefined;
  };
  [key: string]: unknown;
}

export function generateT1Injectable(
  agentName: string,
  config: Record<string, unknown>,
  patterns: string[],
  keyFacts: string[]
): string {
  const model = (config.model as string) || 'deepseek/deepseek-v4-flash';
  const provider = (config.provider || {}) as Record<string, ProviderConfig>;
  const plugins = config.plugin as string[] | undefined;
  const plugin = plugins?.[0] || `file://${TRIDENT_CONFIG.pluginsDir}/${agentName}/dist/index.js`;
  const agentConfig = (config.agent as Record<string, Record<string, unknown>>)?.[agentName] || {};

  let providerJson = '';
  for (const [name, p] of Object.entries(provider)) {
    const pv: ProviderConfig = p || {};
    providerJson += `    "${name}": {\n`;
    providerJson += `      "npm": "${pv.npm || '@ai-sdk/openai-compatible'}",\n`;
    if (pv.options) {
      providerJson += `      "options": {\n`;
      if (pv.options.baseURL) providerJson += `        "baseURL": "${pv.options.baseURL}"\n`;
      if (pv.options.apiKey) providerJson += `        "apiKey": "${pv.options.apiKey}"\n`;
      providerJson += `      }\n`;
    }
    providerJson += `    }\n`;
  }

  let a = `# T1: ${agentName} Injectable\n`;
  a += `**Type:** T1 Injectable (copy-paste into opencode.json)\n`;
  a += `**Agent:** ${agentName}\n`;
  a += `**Model:** ${model}\n`;
  a += `**Status:** Working\n\n`;

  a += `## Container Test Config\n\n`;
  a += `\`\`\`json\n`;
  a += `{\n`;
  a += `  "model": "${model}",\n`;
  if (providerJson) {
    a += `  "provider": {\n${providerJson}  },\n`;
  }
  a += `  "plugin": ["${plugin}"],\n`;
  a += `  "agent": {\n`;
  a += `    "${agentName}": {\n`;
  if (agentConfig.system && typeof agentConfig.system === 'string') a += `      "system": "${agentConfig.system.substring(0, 200)}",\n`;
  a += `      "mode": "primary"\n`;
  a += `    }\n`;
  a += `  },\n`;
  a += `  "permission": {}\n`;
  a += `}\n`;
  a += `\`\`\`\n\n`;

  a += `## Key Configuration Notes\n\n`;
  a += `- Model MUST be at TOP LEVEL: provider-prefix/model-name\n`;
  a += `- Provider MUST have "npm" field for @ai-sdk package\n`;
  a += `- Plugin path MUST use file:// prefix\n`;
  a += `- Agent MUST be OBJECT with mode: "primary"\n`;
  a += `- Permission block REQUIRED for tool execution\n`;
  a += `- Image: opencode-test:1.14.34\n`;
  a += `- Binary: opencode-linux-x64-baseline/bin/opencode (NOT musl)\n\n`;

  if (patterns.length > 0) {
    a += `## Patterns\n\n`;
    for (const p of patterns) { a += `- ${p}\n`; }
    a += `\n`;
  }

  if (keyFacts.length > 0) {
    a += `## Critical Facts\n\n`;
    for (const f of keyFacts) { a += `- ${f}\n`; }
    a += `\n`;
  }

  a += `## Container Test Protocol\n\n`;
  a += `- Image: \`${TRIDENT_CONFIG.containerImage}\`\n`;
  a += `- Binary: \`${TRIDENT_CONFIG.baselineBinary}\`\n`;
  a += `- Snap: \`/tmp/snap-$PROJECT-$TIMESTAMP\` (isolated, NOT host mount)\n`;
  a += `- Wait: 28s for DB migration\n`;
  a += `- Dismiss: Escape for update dialog\n`;
  a += `- Verify: \`tmux capture-pane\` for identity injection\n`;

  a += `\n---\n*Generated by Trident v4.3 Context Synthesis Engine*\n`;
  return a;
}
