import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs/promises';
import { TRIDENT_CONFIG } from '../config.js';
import type { DiscoveryResult } from '../shared/auto-discover.js';

interface ProviderConfig {
  npm?: string;
  options?: {
    baseURL?: string;
    apiKey?: string;
    [key: string]: string | undefined;
  };
  [key: string]: unknown;
}

export function generateT1Injectable(
  agentName: string,
  config: Record<string, unknown>,
  patterns: string[],
  keyFacts: string[]
): string {
  const model = (config.model as string) || 'deepseek/deepseek-v4-flash';
  const provider = (config.provider || {}) as Record<string, ProviderConfig>;
  const plugins = config.plugin as string[] | undefined;
  const plugin = plugins?.[0] || `file://${TRIDENT_CONFIG.pluginsDir}/${agentName}/dist/index.js`;
  const agentConfig = (config.agent as Record<string, Record<string, unknown>>)?.[agentName] || {};

  let providerJson = '';
  for (const [name, p] of Object.entries(provider)) {
    const pv: ProviderConfig = p || {};
    providerJson += `    "${name}": {\n`;
    providerJson += `      "npm": "${pv.npm || '@ai-sdk/openai-compatible'}",\n`;
    if (pv.options) {
      providerJson += `      "options": {\n`;
      if (pv.options.baseURL) providerJson += `        "baseURL": "${pv.options.baseURL}"\n`;
      if (pv.options.apiKey) providerJson += `        "apiKey": "${pv.options.apiKey}"\n`;
      providerJson += `      }\n`;
    }
    providerJson += `    }\n`;
  }

  let a = `# T1: ${agentName} Injectable\n`;
  a += `**Type:** T1 Injectable (copy-paste into opencode.json)\n`;
  a += `**Agent:** ${agentName}\n`;
  a += `**Model:** ${model}\n`;
  a += `**Status:** Working\n\n`;

  a += `## Container Test Config\n\n`;
  a += `\`\`\`json\n`;
  a += `{\n`;
  a += `  "model": "${model}",\n`;
  if (providerJson) {
    a += `  "provider": {\n${providerJson}  },\n`;
  }
  a += `  "plugin": ["${plugin}"],\n`;
  a += `  "agent": {\n`;
  a += `    "${agentName}": {\n`;
  if (agentConfig.system && typeof agentConfig.system === 'string') a += `      "system": "${agentConfig.system.substring(0, 200)}",\n`;
  a += `      "mode": "primary"\n`;
  a += `    }\n`;
  a += `  },\n`;
  a += `  "permission": {}\n`;
  a += `}\n`;
  a += `\`\`\`\n\n`;

  a += `## Key Configuration Notes\n\n`;
  a += `- Model MUST be at TOP LEVEL: provider-prefix/model-name\n`;
  a += `- Provider MUST have "npm" field for @ai-sdk package\n`;
  a += `- Plugin path MUST use file:// prefix\n`;
  a += `- Agent MUST be OBJECT with mode: "primary"\n`;
  a += `- Permission block REQUIRED for tool execution\n`;
  a += `- Image: opencode-test:1.14.34\n`;
  a += `- Binary: opencode-linux-x64-baseline/bin/opencode (NOT musl)\n\n`;

  if (patterns.length > 0) {
    a += `## Patterns\n\n`;
    for (const p of patterns) { a += `- ${p}\n`; }
    a += `\n`;
  }

  if (keyFacts.length > 0) {
    a += `## Critical Facts\n\n`;
    for (const f of keyFacts) { a += `- ${f}\n`; }
    a += `\n`;
  }

  a += `## Container Test Protocol\n\n`;
  a += `- Image: \`${TRIDENT_CONFIG.containerImage}\`\n`;
  a += `- Binary: \`${TRIDENT_CONFIG.baselineBinary}\`\n`;
  a += `- Snap: \`/tmp/snap-$PROJECT-$TIMESTAMP\` (isolated, NOT host mount)\n`;
  a += `- Wait: 28s for DB migration\n`;
  a += `- Dismiss: Escape for update dialog\n`;
  a += `- Verify: \`tmux capture-pane\` for identity injection\n`;

  a += `\n---\n*Generated by Trident v4.3 Context Synthesis Engine*\n`;
  return a;
}

/**
 * generateT2Knowledge — builds the dense, bible-style T2 knowledge markdown.
 * Pure content generation: no disk I/O. Returns the full markdown string.
 *
 * When discovery data is available, produces 500+ lines of rich output.
 * Structure (bible format):
 *   # {ProjectName} — T2 Knowledge Base
 *   ## Agent Identity (with Core Capabilities)
 *   ## Critical Facts (enriched with rationale + consequences)
 *   ## Behavioral Patterns (per-pattern: location, description, code example, anti-pattern)
 *   ## Failure Modes (per-failure: root cause, impact, fix, prevention rule)
 *   ## Design Decisions (with rationale + cost of reversal)
 *   ## Prohibitions (core + dynamically derived + violation consequences table)
 *   ## Context Management Rules (token budget formula, cache triggers, persistence paths)
 *   ## Architecture Summary (component map, data flow diagram, dependency graph, lifecycle)
 *   ## Interface Contracts (exported symbols table, consumer map, contract notes)
 */
export interface KnowledgeFact {
  title: string;
  whyMatters: string;
  whatBreaks: string;
  domain?: 'identity' | 'constraint' | 'architecture' | 'mechanism';
}

export function generateT2Knowledge(
  projectName: string,
  patterns: string[],
  keyFacts: (string | KnowledgeFact)[],
  targetPath?: string,
  discovery?: DiscoveryResult | null
): string {
  const now = new Date().toISOString();
  const projectLabel = projectName.replace(/[_-]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  // ============================================================
  // LOCAL HELPER FUNCTIONS (no new imports required)
  // ============================================================

  /** Map a DiscoveredPattern.type to a human-readable architecture category. */
  const typeCategory = (t: string): string => {
    switch (t) {
      case 'class':     return 'structural';
      case 'interface': return 'structural';
      case 'function':  return 'behavioral';
      case 'import':    return 'architectural';
      case 'export':    return 'structural';
      case 'comment':   return 'architectural';
      default:          return 'behavioral';
    }
  };

  /** Synthesize a representative code snippet for a discovered pattern. */
  const codeExample = (name: string, t: string): string => {
    switch (t) {
      case 'class':
        return [
          'export class ' + name + ' {',
          '  private state: Record<string, unknown> = {};',
          '  constructor(config?: Record<string, unknown>) {',
          '    if (config) Object.assign(this.state, config);',
          '  }',
          '  /** Primary accessor — downstream code calls this. */',
          '  getState(): Record<string, unknown> { return this.state; }',
          '}'
        ].join('\n');
      case 'interface':
        return [
          'export interface ' + name + ' {',
          '  /** Unique identifier for the entity. */',
          '  id: string;',
          '  /** Optional metadata bag; validate before use. */',
          '  metadata?: Record<string, unknown>;',
          '  /** Timestamps in ISO 8601. */',
          '  createdAt?: string;',
          '}'
        ].join('\n');
      case 'function':
        return [
          'export function ' + name + '(input: unknown): Promise<void> {',
          '  if (!input) throw new Error(`' + name + ': input required`);',
          '  // ... core transformation or side effect ...',
          '  return Promise.resolve();',
          '}'
        ].join('\n');
      case 'import':
        return [
          "import { " + name + " } from './module';",
          '// ' + name + ' establishes a dependency edge consumed by the caller.'
        ].join('\n');
      case 'export':
        return [
          'export const ' + name + ' = (data: unknown) => ({',
          '  ok: true as const,',
          '  data,',
          '});'
        ].join('\n');
      default:
        return '// ' + name + ': recognized construct (detail not extractable from static scan).';
    }
  };

  /** Human-readable description of what a pattern does. */
  const describePattern = (name: string, t: string): string => {
    switch (t) {
      case 'class':
        return 'The `' + name + '` class encapsulates state and behavior. It manages lifecycle, '
          + 'holds configuration, and exposes methods invoked by downstream consumers.';
      case 'interface':
        return 'The `' + name + '` interface defines a structural contract. Implementations must '
          + 'conform to its shape; mismatches surface at compile time.';
      case 'function':
        return 'The `' + name + '` function performs a discrete transformation or side effect. '
          + 'It is a callable unit, importable and reusable.';
      case 'import':
        return 'The `' + name + '` symbol is imported from another module, establishing a '
          + 'dependency edge in the import graph.';
      case 'export':
        return 'The `' + name + '` binding is exported as a module boundary, consumable by '
          + 'importers across the codebase.';
      default:
        return 'The `' + name + '` construct is a recognized code pattern at this location.';
    }
  };

  /** Anti-pattern guidance per type. */
  const antiPattern = (t: string): string => {
    switch (t) {
      case 'class':
        return 'Do NOT create a class with only static methods (use a module of functions). '
          + 'Avoid god-classes with more than 10 responsibilities.';
      case 'interface':
        return 'Do NOT use an interface for runtime validation of untrusted data — interfaces '
          + 'are erased at compile time. Use a schema validator instead.';
      case 'function':
        return 'Do NOT make a function both async and side-effectful without documenting the '
          + 'side effect. Avoid returning undefined on success paths.';
      case 'import':
        return 'Do NOT use default imports for modules with named exports — it obscures what '
          + 'is consumed and breaks tree-shaking.';
      case 'export':
        return 'Do NOT export mutable top-level state without a controlled accessor — it '
          + 'creates hidden global coupling.';
      default:
        return 'Do NOT replicate this pattern without understanding its constraints.';
    }
  };

  /** Classify a failure pattern string into a category. */
  const classifyFailure = (pattern: string): string => {
    if (/console\.(error|log|warn)/i.test(pattern)) return 'logging';
    if (/throw\s+new\s+Error/i.test(pattern)) return 'exception';
    if (/catch/i.test(pattern)) return 'catch-block';
    if (/\bany\b/i.test(pattern)) return 'type-erosion';
    return 'unclassified';
  };

  const failureRootCause = (kind: string, message: string): string => {
    switch (kind) {
      case 'logging':
        return 'Logging with message "' + message + '" but without structured context (error ID, '
          + 'request correlation). This makes incident triage slow and non-reproducible.';
      case 'exception':
        return 'An exception is thrown with message "' + message + '". If the caller does not '
          + 'wrap the call in try/catch, the promise rejects unhandled or the process crashes.';
      case 'catch-block':
        return 'A catch block exists near "' + message + '". If the block is empty or only '
          + 'logs, the error chain is severed and the real cause is lost.';
      case 'type-erosion':
        return 'Use of `any` near "' + message + '" erases compile-time type safety, allowing '
          + 'invalid data shapes to flow unchecked.';
      default:
        return 'A failure path exists near "' + message + '" and may not be covered by tests '
          + 'or have graceful degradation.';
    }
  };

  const failureImpact = (kind: string): string => {
    switch (kind) {
      case 'logging':
        return 'Unstructured logs make it impossible to reconstruct the failure timeline during '
          + 'a production incident.';
      case 'exception':
        return 'Unhandled rejection can crash the Node process or leave the container '
          + 'half-initialized, corrupting state.';
      case 'catch-block':
        return 'Silent catch hides bugs: the system reports success while the underlying '
          + 'operation failed, producing corrupt output.';
      case 'type-erosion':
        return 'Type drift propagates downstream: code assumes a shape that is not guaranteed, '
          + 'causing TypeError at runtime.';
      default:
        return 'An untested error path may fire in production with no recovery strategy, '
          + 'degrading or halting the pipeline.';
    }
  };

  const failureFix = (kind: string): string => {
    switch (kind) {
      case 'logging':
        return "Replace with structured log: `tridentLog('ERROR', 'moduleName', message, "
          + "{ requestId, context })` including a unique error ID.";
      case 'exception':
        return 'Wrap the call site in try/catch with explicit recovery, or document that '
          + 'rejection is expected and handle it at the system boundary.';
      case 'catch-block':
        return "Re-throw or log with `tridentLog('ERROR', ...)` and an error ID. Never leave "
          + 'an empty catch body.';
      case 'type-erosion':
        return 'Replace `any` with `unknown` and narrow the type with a type guard or schema '
          + 'validator before use.';
      default:
        return 'Add a test case that exercises this exact path and assert the error is '
          + 'surfaced, not swallowed.';
    }
  };

  const failurePrevention = (kind: string): string => {
    switch (kind) {
      case 'logging':
        return 'Enforce a structured-logging lint rule; ban bare `console.*` calls in CI.';
      case 'exception':
        return 'Add an integration test that asserts the thrown error type and message contract.';
      case 'catch-block':
        return 'Lint rule `no-empty-catch`; code review checklist: "every catch logs or rethrows."';
      case 'type-erosion':
        return 'Enable `noImplicitAny` and `@typescript-eslint/no-explicit-any` at error '
          + 'severity in tsconfig.';
      default:
        return 'Require error-path test coverage in the review gate before merge.';
    }
  };

  // ============================================================
  // BUILD OUTPUT
  // ============================================================

  let b = '';

  // ---- Header ----
  b += '# ' + projectLabel + ' — T2 Knowledge Base\n\n';
  b += '**Type:** T2 Knowledge File (dense, bible-style, standalone artifact)\n';
  b += '**Agent/Project:** ' + projectName + '\n';
  b += '**Generated:** ' + now + '\n';
  b += '**Generator:** Trident v' + TRIDENT_CONFIG.version + ' Context Synthesis Engine\n';
  if (targetPath) {
    b += '**Source Path:** ' + targetPath + '\n';
  }
  b += '\n';
  b += '> This T2 file is the canonical knowledge base for **' + projectLabel + '**. It is '
    + 'dense by design: every section is self-contained and does not require external lookup. '
    + 'Read it in full before modifying this project.\n\n';

  // ============================================================
  // Section 1: Agent Identity
  // ============================================================
  b += '## Agent Identity\n\n';
  b += projectLabel + ' is a Trident-managed agent/project. This T2 knowledge base captures '
    + 'the identity, critical facts, behavioral patterns, failure modes, prohibitions, '
    + 'interface contracts, and architecture discovered during context synthesis.\n\n';
  b += '| Property | Value |\n';
  b += '|----------|-------|\n';
  b += '| Name | ' + projectName + ' |\n';
  b += '| Version | ' + TRIDENT_CONFIG.version + ' |\n';
  b += '| Artifact Type | T2 Knowledge Base |\n';
  b += '| Generator | Trident v' + TRIDENT_CONFIG.version + ' Context Synthesis |\n';
  if (targetPath) {
    b += '| Root Path | ' + targetPath + ' |\n';
  }
  if (discovery) {
    b += '| Source Files | ' + discovery.totalFiles + ' |\n';
    b += '| Source Lines | ' + discovery.totalLines.toLocaleString() + ' |\n';
    b += '| Languages | ' + Object.keys(discovery.languages).length + ' |\n';
    b += '| Entry Points | ' + discovery.entryPoints.length + ' |\n';
  }
  b += '\n';

  b += '### Core Capabilities\n\n';
  b += projectLabel + ' provides the following capabilities to the Trident orchestration layer:\n\n';
  b += '- **Context Synthesis:** Accepts a target project path and produces a T1 Injectable '
    + '(copy-paste-ready opencode.json config) or a T2 Knowledge File (this artifact).\n';
  b += '- **Auto-Discovery:** Scans source directories to extract patterns, failure modes, '
    + 'decisions, entry points, and architectural structure without manual annotation.\n';
  b += '- **Knowledge Encoding:** Transforms raw code intelligence into dense, bible-style '
    + 'markdown that an agent can consume in a single context injection.\n';
  b += '- **Artifact Persistence:** Writes generated artifacts to `'
    + TRIDENT_CONFIG.artifactsBase + '/T2_KNOWLEDGE/` for reproducibility.\n\n';

  // ============================================================
  // Section 2: Critical Facts
  // ============================================================
  b += '## Critical Facts\n\n';
  b += '> Items below are **MUST KNOW** — failure to internalize these causes incorrect '
    + 'behavior, misdirected changes, or silent failures. Each fact includes rationale and '
    + 'consequence.\n\n';

  if (keyFacts.length > 0) {
    for (const f of keyFacts) {
      const factTitle = typeof f === 'string' ? f : f.title;
      b += '### ' + factTitle + '\n';
      if (typeof f === 'string') {
        b += '- **Why it matters:** This fact constrains valid solutions. Ignoring it leads to '
          + 'changes that compile but break runtime invariants or violate project conventions.\n';
        b += '- **What breaks:** If violated, downstream artifacts, tests, or the container '
          + 'runtime may produce incorrect results or fail to initialize.\n';
      } else {
        if (f.whyMatters) b += '- **Why it matters:** ' + f.whyMatters + '\n';
        if (f.whatBreaks) b += '- **What breaks:** ' + f.whatBreaks + '\n';
        if (f.domain) b += '- **Domain:** ' + f.domain + '\n';
      }
      b += '\n';
    }
  } else {
    b += '- **[MUST KNOW]** No critical facts were provided during synthesis. Populate this '
      + 'section with non-obvious, high-impact facts the agent cannot discover from reading '
      + 'code alone — e.g., external API rate limits, required environment variables, or '
      + 'irreversible operations.\n\n';
  }

  if (discovery) {
    b += '### Discovered Facts\n\n';
    b += '- **[MUST KNOW]** **Total source footprint:** ' + discovery.totalFiles + ' files '
      + 'totaling ' + discovery.totalLines.toLocaleString() + ' lines. This defines the scale '
      + 'of changes — small edits are safe; sweeping refactors must be planned.\n';
    b += '- **[MUST KNOW]** **Languages detected:** ';
    if (Object.keys(discovery.languages).length > 0) {
      b += Object.entries(discovery.languages)
        .map(([k, v]) => k + ' (' + v + ' files)').join(', ');
      b += '. The dominant language governs build tooling, lint rules, and test runner.\n';
    } else {
      b += 'none detected (the project may be non-source or excluded by scan filters).\n';
    }
    b += '- **[MUST KNOW]** **Entry points:** ';
    if (discovery.entryPoints.length > 0) {
      b += discovery.entryPoints.map(e => '`' + e + '`').join(', ');
      b += '. These are the module roots — changes here ripple to all importers.\n';
    } else {
      b += 'none detected. The project may rely on implicit resolution or non-standard entry.\n';
    }
    b += '- **[MUST KNOW]** **Warheads found:** ' + discovery.warheads.length;
    if (discovery.warheads.length > 0) {
      b += ' (' + discovery.warheads.join(', ') + ')';
      b += '. Warheads are critical-path declarations that must not be refactored without '
        + 'explicit review.\n';
    } else {
      b += '. No warhead-decorated declarations detected.\n';
    }
    b += '- **[MUST KNOW]** **Audit layers found:** ' + discovery.auditLayers.length;
    if (discovery.auditLayers.length > 0) {
      b += ' (' + discovery.auditLayers.join(', ') + ')';
      b += '. These layers define the review pipeline — new code should pass through them.\n';
    } else {
      b += '. No formal audit layer modules detected.\n';
    }
    b += '\n';
  }

  // ============================================================
  // Section 3: Behavioral Patterns
  // ============================================================
  b += '## Behavioral Patterns\n\n';
  b += '> Code patterns with `file:line` evidence. Follow these when implementing similar '
    + 'functionality. Each pattern includes a representative code example and anti-pattern '
    + 'guidance.\n\n';

  if (discovery && discovery.patterns.length > 0) {
    const shown = discovery.patterns.slice(0, 30);
    b += '_' + shown.length + ' of ' + discovery.patterns.length + ' discovered patterns '
      + 'shown below._\n\n';
    for (const p of shown) {
      const cat = typeCategory(p.type);
      b += '### ' + p.name + ' (' + cat + ')\n';
      b += '- **Location:** `' + p.file + ':' + p.line + '`\n';
      b += '- **Type:** ' + cat + ' (discovery type: `' + p.type + '`)\n';
      b += '- **What It Does:** ' + describePattern(p.name, p.type) + '\n';
      b += '- **Code Example:**\n';
      b += '```typescript\n';
      b += codeExample(p.name, p.type) + '\n';
      b += '```\n';
      b += '- **When to Follow:** When implementing functionality that interacts with `'
        + p.name + '` or builds a similar construct (type: `' + p.type + '`).\n';
      b += '- **Anti-Pattern:** ' + antiPattern(p.type) + '\n\n';
    }
  } else if (patterns.length > 0) {
    b += '_No discovery data available; using ' + patterns.length + ' user-provided patterns._\n\n';
    for (const p of patterns) {
      b += '### ' + p + '\n';
      b += '- **Source:** User-provided pattern (no `file:line` evidence)\n';
      b += '- **Type:** behavioral (convention)\n';
      b += '- **What It Does:** A behavioral convention or structural pattern documented by '
        + 'the project maintainer. Treat as authoritative guidance.\n';
      b += '- **When to Follow:** When the code you are writing matches the described scenario.\n';
      b += '- **Anti-Pattern:** Violating this convention without explicit override and '
        + 'documented justification.\n\n';
    }
  } else {
    b += '- No patterns discovered or provided. Run auto-discovery or supply patterns '
      + 'during synthesis to populate this section.\n\n';
  }

  // ============================================================
  // Section 4: Failure Modes
  // ============================================================
  b += '## Failure Modes\n\n';
  b += '> Error patterns discovered in source code. Each entry includes root cause, runtime '
    + 'impact, recommended fix, and a prevention rule.\n\n';

  if (discovery && discovery.failureModes.length > 0) {
    const shown = discovery.failureModes.slice(0, 20);
    b += '_' + shown.length + ' of ' + discovery.failureModes.length + ' failure modes '
      + 'shown below._\n\n';
    for (const f of shown) {
      const kind = classifyFailure(f.pattern);
      b += '### Failure: ' + f.message + '\n';
      b += '- **Location:** `' + f.file + ':' + f.line + '`\n';
      b += '- **Category:** ' + kind + '\n';
      b += '- **Pattern:** `' + f.pattern + '`\n';
      b += '- **Root Cause:** ' + failureRootCause(kind, f.message) + '\n';
      b += '- **Impact:** ' + failureImpact(kind) + '\n';
      b += '- **Recommended Fix:** ' + failureFix(kind) + '\n';
      b += '- **Prevention Rule:** ' + failurePrevention(kind) + '\n\n';
    }
  } else {
    b += '- No failure modes discovered. This may mean the project is clean, or that the '
      + 'discovery scan was limited. Manually review error-handling paths before production.\n\n';
  }

  // ============================================================
  // Section 5: Design Decisions
  // ============================================================
  b += '## Design Decisions\n\n';
  b += '> Decisions extracted from source comments (marked Decision / Rationale / WHY / REASON).\n\n';

  if (discovery && discovery.decisions.length > 0) {
    for (const d of discovery.decisions) {
      b += '### Decision: ' + d.rationale + '\n';
      b += '- **Location:** `' + d.file + ':' + d.line + '`\n';
      b += '- **Rationale:** ' + d.rationale + '\n';
      b += '- **Alternatives Considered:** Not documented in source. When modifying, verify '
        + 'the original constraint still holds before changing the approach.\n';
      b += '- **Cost of Reversal:** Reversing a documented decision without re-evaluating '
        + 'its rationale risks reintroducing the problem it solved.\n\n';
    }
  } else {
    b += '- No design decisions discovered in source comments. Add comments prefixed with '
      + '`// Decision:` or `// Rationale:` to document non-obvious choices.\n\n';
  }

  // ============================================================
  // Section 6: Prohibitions
  // ============================================================
  b += '## Prohibitions\n\n';
  b += '> What NOT to do. Violating these introduces bugs, regressions, or runtime failures. '
    + 'Each prohibition includes the consequence of violation.\n\n';
  b += '### Core Prohibitions\n\n';
  b += '1. **DO NOT** use sync file I/O (`readFileSync`, `writeFileSync`, `mkdirSync`) in '
    + 'hot paths — use `fs/promises` async equivalents.\n';
  b += '2. **DO NOT** skip layer validation — every mode pipeline layer must call '
    + '`validateLayerContent()` and check the result.\n';
  b += '3. **DO NOT** declare success without runtime evidence — artifacts must be written '
    + 'to disk and verified.\n';
  b += '4. **DO NOT** hardcode paths that should come from `TRIDENT_CONFIG` or environment '
    + 'variables.\n';
  b += '5. **DO NOT** use `require()` in ESM modules — use `import` with `.js` extensions '
    + 'for local files.\n';
  b += '6. **DO NOT** leave empty catch blocks or swallow errors silently — always log with '
    + 'an error ID.\n\n';

  // Dynamic prohibitions derived from discovered failure modes
  if (discovery && discovery.failureModes.length > 0) {
    b += '### Discovered Prohibitions (derived from failure modes)\n\n';
    const derived = new Set<string>();
    for (const f of discovery.failureModes) {
      const kind = classifyFailure(f.pattern);
      let prohibition = '';
      switch (kind) {
        case 'logging':
          prohibition = '- **DO NOT** use bare `console.*` for error logging '
            + '(found at `' + f.file + ':' + f.line + '`) — use structured `tridentLog` instead.';
          break;
        case 'exception':
          prohibition = '- **DO NOT** throw without documenting the error contract '
            + '(found at `' + f.file + ':' + f.line + '`) — callers must know to catch.';
          break;
        case 'catch-block':
          prohibition = '- **DO NOT** leave catch blocks empty or logging-only '
            + '(found at `' + f.file + ':' + f.line + '`) — re-throw or log with an error ID.';
          break;
        case 'type-erosion':
          prohibition = '- **DO NOT** use `any` without a type guard '
            + '(found at `' + f.file + ':' + f.line + '`) — use `unknown` and narrow.';
          break;
        default:
          prohibition = '- **DO NOT** skip error-path coverage '
            + '(failure path found at `' + f.file + ':' + f.line + '`) — add a test.';
          break;
      }
      if (!derived.has(prohibition)) {
        derived.add(prohibition);
        b += prohibition + '\n';
      }
    }
    b += '\n';
  }

  b += '### Violation Consequences\n\n';
  b += '| Prohibition | Consequence |\n';
  b += '|-------------|-------------|\n';
  b += '| Sync I/O in hot paths | Blocks the event loop; container stalls and times out. |\n';
  b += '| Skipped layer validation | Invalid layer content passes to the next stage; pipeline produces garbage. |\n';
  b += '| Success without evidence | Silent false-positive; bug ships to production undetected. |\n';
  b += '| Hardcoded paths | Breaks in different environments; CI vs host mismatch. |\n';
  b += '| `require()` in ESM | Runtime crash: `require is not defined`. |\n';
  b += '| Empty catch blocks | Errors swallowed; data corruption reported as success. |\n';
  b += '| Bare `console.*` logging | Unstructured logs; incident triage takes hours, not minutes. |\n';
  b += '| `any` without guard | Type drift; `TypeError` at runtime in production. |\n\n';

  // ============================================================
  // Section 7: Context Management Rules
  // ============================================================
  b += '## Context Management Rules\n\n';
  b += '> Cache, persistence, and state rules the agent must respect.\n\n';
  b += '### Token Budget\n\n';
  b += '- **Max tokens per injection:** 2000 (T1 layer 3 compression constraint).\n';
  b += '- **Budget formula:** `available = 2000 - (system_prompt_tokens + tool_def_tokens)`.\n';
  b += '- **Scoring formula:** `Score = (Urgency * 0.6) + (Importance * 0.4)`.\n';
  b += '- **Items with Score < 0.3 are dropped** before injection.\n\n';
  b += '### Context Sources\n\n';
  b += '- **T1 (Session):** Runtime session state, active task, in-flight operations.\n';
  b += '- **T2 (Knowledge):** This file — stable project facts, patterns, prohibitions.\n';
  b += '- **T3 (Files):** Source code, configs, test fixtures from the target path.\n';
  b += '- **T4 (Tools):** Tool definitions, capability manifests, permission scopes.\n';
  b += '- Collect from all four layers; omitting any reduces agent effectiveness.\n\n';
  b += '### Cache Invalidation Triggers\n\n';
  b += '- Source files modified since last synthesis -> re-run auto-discovery.\n';
  b += '- `package.json` changed -> re-extract entry points and dependencies.\n';
  b += '- New audit layer added -> re-build the review pipeline definition.\n';
  b += '- T2 artifact older than the newest source file -> stale; regenerate.\n\n';
  b += '### State Persistence\n\n';
  b += '- **Artifacts:** `' + TRIDENT_CONFIG.artifactsBase
    + '/T2_KNOWLEDGE/{projectName}_T2_KNOWLEDGE.md`\n';
  b += '- **T1 injectables:** `' + TRIDENT_CONFIG.artifactsBase
    + '/T1_INJECTABLE/{projectName}_T1.md`\n';
  b += '- **Mode logs:** `' + TRIDENT_CONFIG.artifactsBase + '/logs/`\n';
  b += '- All artifacts survive session end and are reproducible from the target path.\n\n';
  b += '### Evidence Chain Requirements\n\n';
  b += '- Every success claim must cite a `file:line` or a runtime artifact path.\n';
  b += '- Gate evaluation must record `gate`, `passed`, and `notes`.\n';
  b += '- Missing evidence = failed gate, regardless of code correctness.\n\n';
  b += '### Compaction Recovery Protocol\n\n';
  b += '- On context compaction, re-read this T2 file first to restore knowledge.\n';
  b += '- State machine: `orchestrator.completeLayer()` / `orchestrator.failLayer()` must '
    + 'be called for every layer — incomplete layers must be replayed.\n';
  b += '- Mode validation: never skip the validation report in tool output.\n\n';

  // ============================================================
  // Section 8: Architecture Summary
  // ============================================================
  b += '## Architecture Summary\n\n';
  b += '> Discovered structure, data flow, and module relationships.\n\n';

  if (discovery) {
    b += '### Directory Structure\n\n';
    b += '```\n' + discovery.directoryTree + '```\n\n';

    b += '### Component Map\n\n';
    b += '| Component | Role |\n';
    b += '|-----------|------|\n';
    if (discovery.entryPoints.length > 0) {
      b += '| Entry Point(s) | ' + discovery.entryPoints.join(', ')
        + ' — module bootstrap |\n';
    }
    b += '| Patterns (classes) | Object-oriented state encapsulation |\n';
    b += '| Patterns (interfaces) | Structural contracts for type safety |\n';
    b += '| Patterns (functions) | Discrete transformations and side effects |\n';
    b += '| Warheads | ' + (discovery.warheads.length > 0
      ? discovery.warheads.join(', ') : 'None') + ' — critical-path declarations |\n';
    b += '| Audit Layers | ' + (discovery.auditLayers.length > 0
      ? discovery.auditLayers.join(', ') : 'None') + ' — review pipeline |\n\n';

    b += '### Data Flow\n\n';
    b += '```\n';
    b += '                    +-----------------+\n';
    b += '                    |  Target Path    |\n';
    b += '                    |  (source code)  |\n';
    b += '                    +--------+--------+\n';
    b += '                             |\n';
    b += '                             v\n';
    b += '                    +-----------------+\n';
    b += '                    |  Auto-Discovery |\n';
    b += '                    |  (scan + regex) |\n';
    b += '                    +--------+--------+\n';
    b += '                             |\n';
    b += '              +--------------+--------------+\n';
    b += '              v              v              v\n';
    b += '        +----------+   +----------+   +----------+\n';
    b += '        | Patterns |   | Failures |   | Decisions|\n';
    b += '        +-----+----+   +-----+----+   +-----+----+\n';
    b += '              |              |              |\n';
    b += '              +--------------+--------------+\n';
    b += '                             |\n';
    b += '                             v\n';
    b += '                   +-----------------+\n';
    b += '                   |  T2 Knowledge   |\n';
    b += '                   |  (this file)    |\n';
    b += '                   +-----------------+\n';
    b += '```\n\n';

    b += '### Dependency Graph\n\n';
    b += 'Import edges discovered among patterns (derived from import-type discoveries):\n\n';
    const imports = discovery.patterns.filter(p => p.type === 'import');
    if (imports.length > 0) {
      for (const imp of imports.slice(0, 15)) {
        b += '- `' + imp.file + ':' + imp.line + '` imports `' + imp.name + '`\n';
      }
    } else {
      b += '- No explicit import-type patterns detected. Dependency edges inferred from '
        + 'export/import pairs in the codebase.\n';
    }
    b += '\n';

    b += '### Runtime Lifecycle\n\n';
    b += '1. **Bootstrap:** Entry point(s) ';
    if (discovery.entryPoints.length > 0) {
      b += '(' + discovery.entryPoints.join(', ') + ') ';
    }
    b += 'are loaded by the runtime.\n';
    b += '2. **Module Resolution:** Import graph resolves dependencies (see Dependency Graph).\n';
    b += '3. **Initialization:** Constructors and top-level statements execute.\n';
    b += '4. **Steady State:** Exported functions are called by consumers.\n';
    b += '5. **Error Path:** Failures propagate via throw/catch (see Failure Modes).\n';
    b += '6. **Shutdown:** Async resources are flushed; artifacts are persisted.\n\n';

    b += '### Summary Statistics\n\n';
    b += '| Metric | Value |\n';
    b += '|--------|-------|\n';
    b += '| Total Files | ' + discovery.totalFiles + ' |\n';
    b += '| Total Lines | ' + discovery.totalLines.toLocaleString() + ' |\n';
    b += '| Languages | ' + Object.keys(discovery.languages).length + ' |\n';
    b += '| Patterns | ' + discovery.patterns.length + ' |\n';
    b += '| Failure Modes | ' + discovery.failureModes.length + ' |\n';
    b += '| Decisions | ' + discovery.decisions.length + ' |\n';
    b += '| Warheads | ' + discovery.warheads.length + ' |\n';
    b += '| Audit Layers | ' + discovery.auditLayers.length + ' |\n\n';
  } else if (targetPath) {
    b += 'Target path: ' + targetPath + ' (discovery not available — run context synthesis '
      + 'with auto-discovery enabled to populate this section).\n\n';
  }

  b += '### Pipeline Modes\n\n';
  b += '- **CONTEXT_SYNTHESIS** (this artifact): 4-layer pipeline -> T1 Injectable or T2 Knowledge File.\n';
  b += '- **CODE_REVIEW**: 3-stage pipeline -> findings table + fix code.\n';
  b += '- **DEEP_PLANNING**: 3-layer pipeline -> Build Spec + Context Library Manifest.\n';
  b += '- **PROBLEM_SOLVING**: 6-layer pipeline -> reasoning chain + RCA + working plan.\n\n';

  // ============================================================
  // Section 9: Interface Contracts
  // ============================================================
  b += '## Interface Contracts\n\n';
  b += '> Exported symbols, their signatures, and consumer relationships. This section makes '
    + 'the T2 a real engineering reference, not just a summary.\n\n';

  if (discovery && discovery.patterns.length > 0) {
    const exported = discovery.patterns.filter(
      p => p.type === 'export' || p.type === 'function' || p.type === 'class' || p.type === 'interface'
    );
    if (exported.length > 0) {
      b += '### Exported Symbols\n\n';
      b += '| Symbol | Type | Location | Inferred Signature |\n';
      b += '|-------|------|----------|-------------------|\n';
      for (const p of exported.slice(0, 25)) {
        let sig = '';
        switch (p.type) {
          case 'function':
            sig = '`' + p.name + '(input: unknown): Promise<void>`';
            break;
          case 'class':
            sig = '`class ' + p.name + ' { ... }`';
            break;
          case 'interface':
            sig = '`interface ' + p.name + ' { ... }`';
            break;
          case 'export':
            sig = '`const ' + p.name + ': <inferred>`';
            break;
          default:
            sig = '`' + p.name + '`';
        }
        b += '| `' + p.name + '` | ' + p.type + ' | `' + p.file + ':' + p.line + '` | '
          + sig + ' |\n';
      }
      b += '\n';

      // Consumer relationships
      const importSyms = discovery.patterns.filter(p => p.type === 'import');
      if (importSyms.length > 0) {
        b += '### Consumer Map\n\n';
        b += '| Imported Symbol | Imported By | Location |\n';
        b += '|----------------|-------------|----------|\n';
        for (const imp of importSyms.slice(0, 20)) {
          b += '| `' + imp.name + '` | `' + imp.file + '` | line ' + imp.line + ' |\n';
        }
        b += '\n';
      }

      b += '### Contract Notes\n\n';
      b += '- Signatures above are **inferred** from discovery data (name + type only). '
        + 'For exact parameter and return types, read the source at the cited location.\n';
      b += '- Functions discovered as async in source should be treated as returning '
        + '`Promise<T>` even if the inferred signature does not show it.\n';
      b += '- Interfaces define compile-time contracts only — use schema validators for '
        + 'runtime checks on untrusted data.\n\n';
    } else {
      b += '- No exported symbols detected. The project may use default exports or '
        + 'non-standard module patterns not captured by discovery.\n\n';
    }
  } else {
    b += '- Discovery data not available. Interface contracts require an auto-discovery scan '
      + 'of the target path.\n\n';
  }

  b += '\n---\n*Generated by Trident v' + TRIDENT_CONFIG.version
    + ' Context Synthesis Engine — T2 Knowledge Mode*\n';
  return b;
}

export interface T2ArtifactResult {
  content: string;
  path: string;
  preview: string;
  lineCount: number;
  sizeKB: string;
  sections: string[];
}

/**
 * generateT2Artifact — generates the T2 knowledge content via generateT2Knowledge,
 * writes it to disk at {artifactsBase}/T2_KNOWLEDGE/{projectName}_T2_KNOWLEDGE.md,
 * and returns a structured result with metadata (path, preview, size, sections).
 */
export async function generateT2Artifact(
  projectName: string,
  patterns: string[],
  keyFacts: (string | KnowledgeFact)[],
  targetPath?: string,
  discovery?: DiscoveryResult | null
): Promise<T2ArtifactResult> {
  const content = generateT2Knowledge(projectName, patterns, keyFacts, targetPath, discovery);

  // Determine artifact directory from config (fall back to cwd + GENERATED_ARTIFACTS)
  const base = TRIDENT_CONFIG.artifactsBase || path.join(process.cwd(), 'GENERATED_ARTIFACTS');
  const artifactDir = path.join(base, 'T2_KNOWLEDGE');

  await fs.mkdir(artifactDir, { recursive: true });

  const safeName = projectName.replace(/[^a-zA-Z0-9_-]/g, '_');
  const artifactPath = path.join(artifactDir, `${safeName}_T2_KNOWLEDGE.md`);
  await fs.writeFile(artifactPath, content, 'utf-8');

  // Extract section headings for structure overview
  const sections: string[] = [];
  for (const line of content.split('\n')) {
    const m = line.match(/^##\s+(.+)/);
    if (m) sections.push(m[1].trim());
  }

  const lineCount = content.split('\n').length;
  const sizeKB = (Buffer.byteLength(content, 'utf-8') / 1024).toFixed(1);
  const preview = content.substring(0, 500);

  return { content, path: artifactPath, preview, lineCount, sizeKB, sections };
}
