export function generatePlanArtifact(
  targetPath: string,
  problem: string,
  reasoning: string[],
  workingPlan: string[],
  findings: string[]
): string {
  const ts = new Date().toISOString();

  let a = `# PROBLEM-SOLVING PLAN\n\n`;
  a += `**Problem:** ${problem}\n`;
  a += `**Target:** ${targetPath}\n`;
  a += `**Generated:** ${ts}\n`;
  a += `**Status:** INVESTIGATION\n\n`;

  a += `## Reasoning Chain\n\n`;
  a += `| Step | Observation | Hypothesis | Evidence | Conclusion |\n`;
  a += `|------|-------------|------------|----------|------------|\n`;
  reasoning.forEach((r, i) => {
    const parts = r.split('|').map(s => s.trim());
    a += `| ${i + 1} | ${parts[0] || r} | ${parts[1] || 'TBD'} | ${parts[2] || 'TBD'} | ${parts[3] || 'TBD'} |\n`;
  });
  a += `\n`;

  a += `## Root Cause Analysis\n\n`;
  a += `| Field | Detail |\n`;
  a += `|-------|--------|\n`;
  a += `| **Symptom** | ${reasoning[0] || problem} |\n`;
  a += `| **Root Cause** | ${reasoning.length > 1 ? reasoning[reasoning.length - 1] : 'Under investigation'} |\n`;
  a += `| **Contributing Factors** | ${findings.slice(0, 3).join('; ') || 'None identified'} |\n`;
  a += `| **Impact Scope** | ${targetPath} and dependent modules |\n`;
  a += `\n`;

  a += `## Working Plan\n\n`;
  a += `| Phase | Description | Files | Expected Outcome | Risk | Rollback |\n`;
  a += `|-------|-------------|-------|------------------|------|----------|\n`;
  workingPlan.forEach((p, i) => {
    const parts = p.split('|').map(s => s.trim());
    a += `| ${i + 1} | ${parts[0] || p} | ${parts[1] || 'TBD'} | ${parts[2] || 'Fix applied'} | ${parts[3] || 'LOW'} | ${parts[4] || 'git checkout'} |\n`;
  });
  a += `\n`;

  a += `## Findings Log\n\n`;
  a += `| # | Finding | Severity | Source |\n`;
  a += `|---|---------|----------|--------|\n`;
  findings.forEach((f, i) => {
    a += `| ${i + 1} | ${f} | TBD | Investigation |\n`;
  });
  a += `\n`;

  a += `## Verification Checklist\n\n`;
  a += `- [ ] Symptom no longer reproduces\n`;
  a += `- [ ] Root cause confirmed fixed (not just symptom masked)\n`;
  a += `- [ ] No new regressions introduced\n`;
  a += `- [ ] Test suite passes (or new tests added)\n`;
  a += `- [ ] Container TUI test passes\n`;
  a += `\n`;

  a += `## Regression Prevention\n\n`;
  a += `- Add test case that reproduces original symptom\n`;
  a += `- Add audit layer check for this failure pattern\n`;
  a += `- Update context library with this failure mode\n`;

  a += `\n---\n*Generated by Trident v4.3 Problem-Solving Engine*\n`;
  return a;
}
