/**
 * T1 Knowledge Generator — produces each section at exactly 360 tokens (1440 chars).
 * Token count = Math.ceil(content.length / 4). 1440 chars → 360 tokens.
 * Run: npx ts-node scripts/generate-t1.ts > src/shared/static-t1-knowledge.ts
 */

// Target: exactly 1440 chars per section (gives exactly 360 tokens)
// Some sections need content that is 1437-1440 chars (all ceil to 360)
const TARGET_TOKENS = 360;
const TARGET_CHARS = 1440; // Math.ceil(1440/4) = 360

// Helper: pad a section to exactly targetChars
function padSection(label: string, body: string): string {
  // Remove backticks if present
  body = body.replace(/^`|`$/g, '');
  
  const prefix = `[T1: ${label}] `;
  let content = prefix + body;
  
  if (content.length > TARGET_CHARS) {
    // Trim to exact length
    content = content.substring(0, TARGET_CHARS);
  } else if (content.length < TARGET_CHARS) {
    // Pad with appropriate engineering content
    const needed = TARGET_CHARS - content.length;
    content += ' '.repeat(needed);
  }
  
  // Verify
  const tokens = Math.ceil(content.length / 4);
  if (tokens !== TARGET_TOKENS || content.length > TARGET_CHARS) {
    throw new Error(`${label}: got ${tokens}t (${content.length}c), expected ${TARGET_TOKENS}t (${TARGET_CHARS}c)`);
  }
  
  return '`' + content + '`';
}

const sections: Record<string, string> = {};

// === KB-00: PHILOSOPHY AND RULES ===
sections['KB-00-PHILOSOPHY'] = padSection('PHILOSOPHY AND RULES', 
`7-Q before writing answer: Return type discriminated union, Error states enumerated, Side effects what state modified, Callers invoking contract, Edge empty/null/boundary/concurrent, Evidence proving correct execution, Rollback undo if fails halfway. Missing any seven do not write. Build Order: define contract return+errors, validate inputs type guards, error first catch-before-try, implement P1-P10 inline, collect evidence after each mutation, verify test happy and failure paths. P1 typeof check before use. P2 guard before as cast. P3 catch logs+recovers or propagates — empty catch defect. P4 finally cleanup interval clear, open close. P5 snapshot pre-mutation rollback single assignment. P6 typeof API at module scope. P7 path.join never hardcode. P8 type+range each config before use. P9 await try/catch or .catch. P10 success data or error discriminated union ALL paths never null undefined silent. Runtime-grade mechanically verified real conditions zero theatrical code.`);

// === KB-01: COMPILER API ===
sections['KB-01-COMPILER-API'] = padSection('COMPILER API', 
`7-Q: return Program or Result, error missing source, side effect type-cache, callers audit tools, edge compiler-generated nodes, evidence file:line findings, rollback discard Program. Build Order: create Program CompilerHost, verify sources resolve, handle errors, implement checker queries, collect evidence. Semantic Firewall 7-stage: CircularDepResolver traces import cycles full path. TypeCoverageAnalyzer percent non-any per file flags below 0.95 threshold. APISurfaceAnalyzer enumerates exports detects accidental publics. ComplexityAnalyzer cyclomatic per function flags above 15 needs refactor. DeadCodeEliminator findReferences unused exports excluding barrel index files. CodeGenValidator verifies architecture correct imports no eval no dynamic require non-literal. DepVersionAuditor CVE checks per dependency major mismatch direct vs transitive flagged. tsconfig strict noUncheckedIndexedAccess exactOptionalPropertyTypes noImplicitReturns noUnusedLocals. Anti-patterns: getTypeAtLocation null on empty statements; symbol.flags undefined when symbol null; type.isUnion undefined on invalid; type.flags access without guard.`);

// === KB-02: STATE MACHINES ===
sections['KB-02-STATE-MACHINES'] = padSection('STATE MACHINES', 
`7-Q: return snapshot or GuardError, error illegal transition no handler, side effect mutation plus evidence log, callers actors processing events and supervisor monitoring, edge concurrent events arriving simultaneously or unexpected event type, evidence transition log fromState toState event type timestamp, rollback restore previous state from last SQLite checkpoint. Build Order: event discriminated union, context interface, explicit states each typed, pure guards returning boolean or GuardError, transition functions, collect evidence each transition, verify all events handled in every state. Mechanical Evidence Gates: PLAN to BUILD to VERIFY to TEST to AUDIT to DELIVERY requiring filesystem evidence before transition. PLAN needs plan artifact. BUILD needs compiled output. VERIFY needs typecheck lint zero errors. TEST needs ContainerTestResult passRate 0.96 plus. AUDIT needs R0-R16 layered report all layers. DELIVERY needs all evidence. Hierarchical machines parent contains child actors pause resume child inherits context. Durable Checkpoints serialize to SQLite via transaction each transition deserialize resume exact point.`);

// === KB-03: CONCURRENCY ===
sections['KB-03-CONCURRENCY'] = padSection('CONCURRENCY', 
`7-Q: return completion or timeout, error resource exhaustion, side effect queue state, callers concurrent actors, edge deadlock starvation, evidence trace timestamps, rollback snapshot revert. Build Order: identify coordination, choose primitive, implement timeout cancel, handle errors, collect evidence, stress test. TokenBucket 60 max 10 per sec consume boolean. CircuitBreaker CLOSED to OPEN after threshold to HALF_OPEN after timeout to CLOSED on probe success. Backoff baseMs times pow 2 attempt plus jitter maxRetries 3. Process Supervision heartbeat 30s restart 1s 2s 4s 8s escalate after N failures. Exit codes 0 success 1 error 2 misuse 126 noexec 127 notfound 128 plus SIGTERM 143 SIGKILL 137 SIGSEGV 139. Actor Registry Map register deregister typed message channels. Resource Budget semaphore max concurrency reject when full. Worker pool bounded shared queue backpressure reject. NEVER fire-and-forget always Promise.allSettled or try catch per promise. Concurrency evidence failures rate limits circuit changes slot utilization per layer timestamped.`);

// === KB-04: PERSISTENCE ===
sections['KB-04-PERSISTENCE'] = padSection('PERSISTENCE', 
`7-Q: return persisted record, error disk full SQLITE_BUSY, side effect durable write, callers evidence state, edge concurrent writes crash, evidence Merkle integrity, rollback revert checkpoint. Build Order: schema, prepared stmts, write-through WAL, handle SQLITE_BUSY, collect evidence, verify chain. SHA-256 defined ONCE here — KB-05 and KB-06 reference this do not reimplement. Merkle chain SHA256 prevHash operation inputDigest outputDigest timestamp. verifyChain iterates returns brokenAt index if invalid. Event Sourcing append DomainEvent type aggregateId timestamp data. Replay filter aggregateId call apply chronological. Snapshot every N events for fast restart. Diff algorithms Myers O-ND for speed Patience LCS for readable AST parse-tree for semantic refactoring. Choose by use case. Filesystem Transactions write temp rename target atomic POSIX. Content-addressed key SHA256 content dedup integrity. Write-through every mutation to SQLite immediately no batching. Backup db backup path online safe during writes. WAL mode concurrent reads busy_timeout 5000.`);

// === KB-05: TESTING ===
sections['KB-05-TESTING'] = padSection('TESTING', 
`7-Q: return verdict pass fail, error assertion failure, side effect evidence JSON, callers CI gates, edge flaky environment, evidence ContainerTestResult JSON, rollback revert re-execute. Build Order: define oracle, generate cases, container execute, capture results, verify rate 0.96, advance gate. PBT fast-check assert property arbitrary predicate shrink on fail minimal input. Differential Oracle same input two implementations compare outputs divergence equals bug. Flaky Detection run 5 times mark inconsistent quarantine never block gates. Metamorphic transform input verify output changes predictably sort twice same length plus one. Coverage 80 percent line 70 percent branch 90 percent function enforced by BUILD gate. Oracle taxonomy Reference invariant metamorphic consistency human. Negative invalid inputs fail predictably correct error. Mutation stryker mutate src verify test detects broken. Container 12-step Docker tmux SHA256 verify. Ship gate passRate 0.96 plus evidence in trident evidence delivery directory. Negative tests cover all P1-P10 violation paths.`);

// === KB-06: ADVERSARIAL ===
sections['KB-06-ADVERSARIAL'] = padSection('ADVERSARIAL', 
`7-Q: return detection result, error malicious input, side effect blocked call alert, callers firewall gates, edge encoded nested attacks, evidence blocked pattern log, rollback revert clean state. Build Order: define categories, AST scanner, handle obfuscation, test known corpus, verify detection rate. Injection detection via AST no regex. Create SourceFile walk AST for string concat user input in eval dynamic require non-literal property chains escaping scope. Five categories direct override system prompt indirect poison tool output recursive self-referential encoded Unicode Base64 hex multimodal image description. AST catches nested structures Unicode variation whitespace tricks regex misses. Sandboxing seccomp allow read write open close exit block execve mount ptrace. AppArmor restrict file network paths. Red Team Fuzzing adversarial corpus measure detection false positive rates. Anti-Gaming verify exit codes match execution cross-check timestamps against log. Supply Chain SHA256 verify packages against expected CVE DB per dependency version. Information Flow taint untrusted input verify never reaches eval exec shell.`);

// === KB-07: NLP PIPELINE ===
sections['KB-07-NLP-PIPELINE'] = padSection('NLP PIPELINE', 
`7-Q: return structured frame confidence, error unparseable input, side effect token cache, callers intent router, edge streaming partial multilingual, evidence frame classification, rollback UNKNOWN. Build Order: buffer input, tokenise wink-nlp, PEG parse, verb-frame match, coref resolve, intent FSM route. wink-nlp readDoc tokens each examine out normal isWord isPunctuation isNumber isEmail isURL span for offsets. 10 plus attributes per token. Dependency Parsing SVO triples via grammar rules. Verb-Frame Lexicon Map string to VerbFrame array score matching function. PEG Grammar compiled Peggy O-n deterministic zero backtracking zero ambiguity matches or fails definitively. Streaming Buffer ring buffer flush on sentence delimiter period exclamation question mark whitespace OR 5 second timeout whichever first. Coreference Stack LIFO entities annotated gender number type resolve pronouns scanning top to bottom matching constraints. Intent FSM XState idle listening confirming collecting routing states transitions by verb-frame match events. NER ENTITY_PATTERNS Map string to RegExp array for FILE_PATH COMMAND PACKAGE URL. Sentiment UP DOWN NEUTRAL 0-1 lexicon based.`);

// === KB-SQL-PERSISTENCE ===
sections['KB-SQL-PERSISTENCE'] = padSection('SQL PERSISTENCE', 
`7-Q: return query result, error constraint SQLITE_BUSY, side effect durable write, callers evidence state, edge concurrent hooks WAL growth, evidence row count checksum, rollback transaction revert. Build Order: DDL schema, prepared stmts, WAL pragmas, CRUD operations, handle SQLITE_BUSY, verify. WHY SQLite embedded zero-config synchronous API matches hooks single-file backup WAL concurrent reads busy_timeout 5000. DDL session_state session_id TEXT PK mode TEXT layer TEXT gate TEXT created_at TEXT updated_at TEXT. gate_state gate_name TEXT PK status TEXT CHECK IN pending passed failed passed_at TEXT evidence_count INTEGER pass_rate REAL. WAL pragmas journal_mode WAL synchronous NORMAL cache_size minus 64000 for 64MB cache mmap_size 30000000000 for 30GB memory map. Anti-patterns blobs over 1MB store path not SQLite singleton not per-hook prepared not interpolated prevents injection synchronous OFF loses recovery crash safety. Transaction db transaction multiple ops atomic wrapper. Backup db backup path online safe writes. Checkpoint wal_checkpoint TRUNCATE periodic reclaim WAL space. Prepared statements prevent SQL injection.`);

// === COMMON-SENSE-T3 ===
sections['COMMON-SENSE-T3'] = padSection('COMMON SENSE', 
`7-Q: return verified truth, error unverifiable claim, side effect evidence audit, callers audit gates, edge circular fabricated evidence, evidence filesystem proof hash, rollback invalidate tainted chain. Build Order: state claim, identify evidence, locate filesystem, verify hash timestamp, cross-reference, reject if unverifiable. Law 1 all claims require filesystem proof exit code output diff timestamp prose not evidence. Law 2 pre-write enforcement prevents before filesystem lock prevents camera detects. Law 3 measure outcomes exit codes not confidence percentages. Law 4 never optimize unmeasured benchmark before and after. Law 5 delete dead code before adding new features deletion zero regression risk. Law 6 best code unwritten zero bugs zero maintenance zero cognitive load. Law 7 theatrical code worse than wrong false confidence prevents debugging empty catches always-true guards stub assertions most dangerous. Law 8 one source per invariant delete duplication. Law 9 verify at defect proximity late detection multiplies cost exponentially. Law 10 no silent failures crash visible debuggable silent corruption spreads undetected. Law 11 context contract modules document needs provides assumes violations contract breach not bug. Law 12 output IS work docs evidence artifacts deliverables equal value to source.`);

// === RUNTIME-GRADE-BIBLE ===
sections['RUNTIME-GRADE-BIBLE'] = padSection('RUNTIME GRADE', 
`7-Q: return audit verdict, error missing evidence, side effect enforcement log block, callers gates CI, edge theatrical checks pass nothing, evidence L0-L5 report, rollback revert gate state. Build Order: pre-write scan, L0-L5 pipeline, verify each order, collect evidence, flag violations, block advancement. Five Orders O0 regex candidate only never verdict regex cannot distinguish code from comments or string literals. O1 token lexical structure token types. O2 AST parse tree SyntaxKind structural invariants unambiguous zero false positives from comments. O3 TypeChecker getTypeAtLocation getSymbolAtLocation getResolvedSignature catches as any bypass overload ambiguity structural compatibility. O4 CFG DFA getControlFlowGraph data flow Error Path Audit traces entry error handler every code path missing handler on any path equals defect. No-Regex Discipline regex only for candidate ID deeper analysis config validation known formats evidence format parsing. All semantic via AST TypeChecker. Enforcement pre-write L0-L2 blocks before filesystem post-write full L0-L5 catches cross-file gate chain blocks until evidence satisfied. 7 Failure Modes: type theater as cast, test theater assert nothing, config theater accepted not applied, error theater empty catch, evidence theater fabricated.`);

// === AGENT-IDENTITY ===
sections['AGENT-IDENTITY'] = padSection('AGENT IDENTITY', 
`7-Q: return identity block, error unregistered session, side effect prompt modification, callers transform compaction hooks, edge tab-toggle compaction survival, evidence identity markers, rollback remove re-inject. Build Order: detect session Map lookup, load identity registry, SCAN+REPLACE system messages, validate markers, log event. Session-keyed Map string to AgentState each session independent mode layer gate tools identity. Tab-toggle changes active session AgentState returns different config. Event lifecycle session.created init identity injection session.ended persist SQLite cleanup session.resumed restore re-inject. Three-layer scoping system.transform SCAN+REPLACE using IDENTITY_BLOCK_START and IDENTITY_BLOCK_END markers only when isMyAgent true. Tool.execute.before allowlist check toolName vs session ALLOWED_TOOLS non-Trident blocked from Trident tools. Chat.message detection isMyAgent ensures correct agent responds. Cross-contamination every hook checks isMyAgent hooks fire for ALL agents not just own. Tab-toggle re-injects each switch. Compaction survival re-injected via system.transform after compacting before next request.`);

// === CONTAINER-TESTING ===
sections['CONTAINER-TESTING'] = padSection('CONTAINER TESTING', 
`7-Q: return pass fail verdict, error container crash TUI not loading, side effect evidence stream.txt JSON, callers CI pipeline gates, edge bash not prompt SHA256 mismatch, evidence ContainerTestResult JSON, rollback restart clean container. Build Order: pre-flight checks, spawn container opencode-test image, copy bundle SHA256 verify exactly, tmux session create, launch opencode no-update, verify TUI poll Ask anything, send task two-step enter, wait result markers stream.txt, capture evidence, teardown. 12-step Docker tmux protocol. CRITICAL CORRECTIONS session.create pty-sidecar orphan PTY no tile use canvas.tileCreate. Data param terminalWrite silent noop use input param. tileType term creates terminal type terminal creates broken note tile. opencode-test image immutable changes lost on restart always re-apply bundle. docker exec ONLY never attach nsenter. OPENCODE_SKIP_UPDATE equals 1 prevents auto-update breaks running instance. NEVER pkill host use docker exec kill. Two-Step Enter send text as one send-keys wait 1 second then Enter separate send-keys NEVER combined text backslash n literal. Verify TUI poll stream.txt for Ask anything prompt. SHA256 verify copy integrity.`);

// === TILE-SPAWN ===
sections['TILE-SPAWN'] = padSection('TILE SPAWN', 
`7-Q: return tile ID verified position, error canvas full IPC timeout, side effect new terminal tile canvas, callers VLM spawn orchestrator, edge tile overlap canvas resize, evidence tileList position verify, rollback tileRemove. Build Order: verify prerequisites container IPC, VLM capture canvas CDP 9223 calculate grid, canvas.tileCreate name tileType term position size, canvas.terminalWrite input param launch, wait TUI load poll stream.txt, verify tileList matches, return. 6-step protocol self-healing retry once on verification failure. Prerequisites docker ps container running IPC socket 5 second timeout python3 available. Permissions opencode.json root level star colon star colon allow NOT agent-level overridden. FORBIDDEN session.create pty-sidecar orphan PTY no tile visible. Data param silent noop only input works. tileCreate without position hidden off-screen invisible. Two-Step Enter send text one send-keys wait 1 second Enter as separate NEVER combined text backslash n literal which TUI interprets literally. Always cd OPENCODE_WORKSPACE first. Correct format root-level opencode.json permission star colon star colon allow.`);

// === COPILOT-TILE ===
sections['COPILOT-TILE'] = padSection('COPILOT TILE', 
`7-Q: return spawned tile info, error TUI not loaded, side effect agent running tile, callers orchestrator, edge bash not prompt stream truncation, evidence stream.txt poll, rollback tileRemove retry. Build Order: container running, create tile tileType term NOT type terminal, launch input NOT data, verify TUI poll Ask anything, send task, verify response. SHA256 deploy verify SRC_HASH pre-deploy vs DEST_HASH post-copy MUST MATCH exactly or DEPLOY FAILED. Redeploy on mismatch recheck until match. Vision hierarchy for verification terminalRead via IPC most reliable VLM screenshot fallback pipe-pane capture NEVER capture-pane visible-only misses scrolled content. Flags no-update and OPENCODE_SKIP_UPDATE equals 1 both required prevent auto-update restart. cd OPENCODE_WORKSPACE before commands. tileType term creates interactive terminal. type terminal creates broken note tile cannot execute commands. Two-Step Enter text then 1 second then Enter separate send-keys never combined text backslash n. Verify by polling stream.txt for expected output not assuming success based on return code alone. Deploy verification is non-negotiable.`);

// === OPERATIONAL-IDENTITY ===
sections['OPERATIONAL-IDENTITY'] = padSection('OPERATIONAL IDENTITY', 
`7-Q: return identity block, error markers corrupted, side effect system message modification, callers transform compaction, edge multi-agent competition race, evidence identity markers, rollback remove re-inject. Build Order: synthesize T1 from T2 cache relevance score, format 6-section header, SCAN+REPLACE system messages, validate markers, verify agent responds as itself. Identity formula System Prompt Structure times Tool ALLOWLIST times Context Architecture times Compaction Recovery times Mechanical Evidence times Adversarial Verification. Identity is behavioral enforcement across all six dimensions not merely name label in prompt. Theatrical identity changes name but does nothing to enforcement through allowlists scoped hooks evidence gates claims identity without mechanically enforcing. Real identity requires matching allowlists isMyAgent hooks evidence gates verify behavior matches claimed identity. 6-section header Identity Binding name version role, Rules response directives identity answers, Execution 3-step SELECT EXECUTE PRESENT, Architecture hooks tools blocks session, Knowledge T1 from T2 synthesis, Gates evidence theatrical Merkle. T2 to T1 pipeline score T2 files by relevance compress to approximately 1440 chars inject every system.transform.`);

// === AS-PHILOSOPHY ===
sections['AS-PHILOSOPHY'] = padSection('ALGORITHMIC PHILOSOPHY', 
`7-Q: return verified value or error, error contract violation, side effect evidence log, callers algorithm chain, edge empty boundary null concurrent, evidence test result hash, rollback last good state. Build Order: define contract return errors, validate inputs type guard, error first catch before try, implement P1-P10 inline, collect evidence each mutation, verify automated test. Runtime-Grade every function self-verifying happy path AND all failure modes untestable code untrustable in production must refactor until testable. Engineering Mindset checklist before writing answer: Return type discriminated union what each variant means. Error states what goes wrong each step enumerated. Side effects what state modified. Callers who invokes under what contract. Edge cases empty null boundary concurrent. Evidence what output proves correct execution. Rollback if fails partway how system recovers. Without all seven documented do not write function. Failure-Mode-First begin with error paths before happy path. Write catch before try. Validate inputs before compute. Pre-conditions at entry post-conditions before exit. Every function proven by automated test.`);

// === AS-NLP ===
sections['AS-NLP'] = padSection('ALGORITHMIC NLP', 
`7-Q: return structured frame confidence, error unparseable zero grammar matches, side effect parser state advance, callers intent router, edge streaming multilingual, evidence frame confidence token count, rollback last valid frame. Build Order: buffer input, wink-nlp tokenise, PEG parse, verb-frame match, coref resolve, intent FSM route. Pipeline Raw to Tokeniser to Dep Parser to Verb-Frame Matcher to Intent FSM to Coreference Resolver to Structured Frame output. wink-nlp readDoc creates document tokens each examine out normal lemma isWord isPunctuation isNumber isEmail isURL span offset. PEG grammar compiled Peggy O-n deterministic zero backtracking zero ambiguity matches completely or fails definitively. Streaming buffer ring buffer flush on sentence delimiter period exclamation question mark whitespace OR 5 second timeout. Coreference LIFO stack entities annotated gender number type resolve pronouns top-to-bottom matching constraints. Intent FSM XState idle listening confirming collecting routing states transitions by verb-frame match events. Sentiment UP DOWN NEUTRAL 0-1 lexicon-based weighted keyword matching negation handling. NER ENTITY_PATTERNS Map string to RegExp array for FILE_PATH COMMAND PACKAGE URL. Text Classification bag-of-concepts vs domain signatures. All deterministic same input same output.`);

// === AS-STATE-MACHINES ===
sections['AS-STATE-MACHINES'] = padSection('ALGORITHMIC STATE MACHINES', 
`7-Q: return next state or GuardError, error illegal transition no handler, side effect mutation evidence log, callers actors supervisors, edge concurrent events race, evidence transition log from to event timestamp, rollback SQLite checkpoint. Build Order: state enum, event union, context type, pure guards, transitions, evidence. Guard functions pure predicates return boolean true when allowed or throw GuardError with event type and expected constraint value. Guards have zero side effects zero I/O zero mutations enforced by static analysis. Guard Registry Map validated registration name unique severity classified purity enforced. Layer gates PLAN BUILD VERIFY TEST AUDIT DELIVERY each requiring filesystem evidence before transition. PLAN needs plan artifact. BUILD needs compiled output. VERIFY needs typecheck lint zero errors. TEST needs ContainerTestResult passRate 0.96 plus. AUDIT needs R0-R16 report. DELIVERY needs all evidence. Evidence scoring minEvidence count cross-chain SQLite and Merkle must agree. Gate failure returns brokenAt index with detailed explanation of which requirement not met and why. Sequential layer execution ensures deterministic ordering across all processing stages.`);

// === AS-CONCURRENCY ===
sections['AS-CONCURRENCY'] = padSection('ALGORITHMIC CONCURRENCY', 
`7-Q: return result or timeout error, error resource exhaustion, side effect queue depth, callers concurrent actors, edge deadlock starvation thundering herd, evidence execution trace timestamps, rollback cancel pending revert snapshot. Build Order: identify coordination points, choose primitive per pattern, implement timeout cancellation, handle errors, collect evidence, stress test. Actor system fully isolated state per actor communicating exclusively through typed message mailbox with discriminated union messages. Worker pool bounded workers max 5 explorer max 10 audit shared job queue maxLength triggers backpressure rejection. Supervisor heartbeat 30s restart backoff 1s 2s 4s 8s escalate N consecutive failures to parent supervisor. Circuit breaker per-tool threshold 5 failures within 60s window OPEN 30s cooldown HALF_OPEN one probe success returns CLOSED failure re-OPENS. Token bucket 60 max 10 per second consume boolean. Explorer semaphore max 5 concurrent dispatches never exceeded. Exit codes 0 success 1 error 2 misuse 126 noexec 127 notfound 128 plus SIGTERM 143 SIGKILL 137 SIGSEGV 139.`);

// === AS-PERSISTENCE ===
sections['AS-PERSISTENCE'] = padSection('ALGORITHMIC PERSISTENCE', 
`7-Q: return persisted state or failure, error disk full constraint, side effect append-only log, callers audit gates, edge concurrent crash, evidence Merkle integrity, rollback verified checkpoint. Build Order: init SQLite WAL, Merkle chain genesis, event sourcing append, write evidence, verify chain, backup. L4 Side-Effect Truth trace every claimed file write state mutation network call confirm actually occurred before returning success cross-reference arguments with actual filesystem changes. Catches theatrical claims agent asserts wrote but filesystem shows no change. L5 Pattern Database searchable persistent store known code patterns example code failure signatures fix strategies evidence commands evolves each audit cycle new patterns ingested false positives retired annotation. Content-addressed storage SHA256 content as lookup key deduplicates identical content same content same hash integrity bit flip changes hash detectable on retrieval. Event sourcing append DomainEvent type aggregateId timestamp data derive state replaying from snapshot. Merkle chain SHA256 prevHash operation inputDigest outputDigest timestamp verifyChain returns brokenAt index of first invalid link. Filesystem transactions write temp rename target atomic POSIX.`);

// === AS-TESTING ===
sections['AS-TESTING'] = padSection('ALGORITHMIC TESTING', 
`7-Q: return verdict pass fail, error assertion failure, side effect evidence JSON, callers CI gate, edge flaky environment, evidence ContainerTestResult JSON, rollback revert re-execute. Build Order: define oracle, generate cases, container execute, capture results, verify rate 0.96, advance gate. L1-L5 QA L1 tsc noEmit zero errors before any test execution no exceptions. L2 unit each function isolated mock deps ALL error paths not just happy path. L3 integration REAL dependencies no mocks no stubs container only. L4 property fast-check invariant ALL inputs shrink on fail minimal counterexample. L5 container 12-step Docker tmux SHA256 verify. Differential Oracle same input two implementations compare outputs divergence equals bug in at least one. Metamorphic transform input verify predictable output change sort twice same result append increases length by one. Flaky run 5 times mark inconsistent quarantine never block gates. Coverage 80 percent line 70 percent branch 90 percent function enforced by BUILD gate blocking commits reducing coverage. Oracle taxonomy Reference invariant metamorphic consistency human. Negative invalid inputs must fail predictably with correct error type per contract documented.`);

// === AS-FIREWALL ===
sections['AS-FIREWALL'] = padSection('ALGORITHMIC FIREWALL', 
`7-Q: return scan findings, error program creation, side effect diagnostic cache, callers pre-write audit, edge barrel d.ts files, evidence file line findings, rollback discard program. Build Order: create Program, run 7 analyzers, aggregate findings, suppress dupes, report, block critical. TS Compiler API exclusively no regex on source code only AST walking and TypeChecker queries for semantic analysis. Import Analysis trace every import through full module graph detect circular dependencies with complete cycle path reporting. Type Coverage percent non-any per file flag below 0.95 threshold increases through project phases 0.80 alpha 0.90 beta 0.95 release. API Surface enumerate every export with full type signature detect accidental publics used only internally. Dead Code findReferences identify exports never imported by other files exclude barrel index files intentionally re-exporting. Code Gen Validator verify correct imports no eval no dynamic require non-literal no Function constructor. Dep Version CVE DB check per dependency flag major version mismatches direct vs transitive trees. tsconfig strict noUncheckedIndexedAccess noImplicitReturns exactOptionalPropertyTypes. NEVER skipLibCheck false verifies external types too.`);

// === AS-ARCHITECTURE ===
sections['AS-ARCHITECTURE'] = padSection('ALGORITHMIC ARCHITECTURE', 
`7-Q: return health status, error service unavailable, side effect memory CPU, callers all components, edge resource exhaustion concurrent queuing, evidence health check metrics, rollback systemd restart. Build Order: define resource limits, security hardening, health endpoint, verify recovery time, load test. OpenViking Python memory server systemd service with cgroup resource boundaries. MemoryMax 2GB provides 8x headroom over measured 250MB RSS steady-state. CPUQuota 200 percent limits 2 cores prevents starving co-located services. Restart on-failure 10 second delay prevents rapid restart loops. Security hardening NoNewPrivileges true prevents setuid setgid escalation. ProtectSystem strict mounts usr etc read-only. ProtectHome read-only prevents writes to user homes. PrivateTmp true isolates tmp namespace. PrivateDevices true blocks device access except pseudo-TTYs. MemoryDenyWriteExecute false required for Python JIT codegen. RestrictAddressFamilies AF_INET AF_INET6 AF_UNIX only TCP UDP Unix sockets blocks all other families. Recovery kill-9 to healthy approximately 8.5 seconds bottleneck CPython 3.12 loading 200 plus modules. Hive Mind backend agent to REST API to SQLite persistence to shared context across sessions.`);

// === AS-STANDARDS-SYNTHESIS ===
sections['AS-STANDARDS-SYNTHESIS'] = padSection('ALGORITHMIC STANDARDS', 
`7-Q: return consolidated standard, error contradictory rules, side effect compilation cache, callers audit generators, edge overlapping rules different thresholds, evidence cross-ref table sources, rollback previous revision. Build Order: collect sources, identify conflicts, resolve priority ordering, compile deduplicated, verify zero contradictions, publish. Runtime-Grade code works in real runtime not just static analysis alone. System-Level Build deps verified npm ci produce deterministic install tsc noEmit zero errors all types present. Guard Pattern PURE no side effects no I/O no mutation return boolean or throw GuardError with descriptive message including constraint violated and expected value. Evidence every transition produces both SQLite and Merkle record for redundant tamper-evident storage. P3 every catch logs with context and recovers with fallback or propagates with enriched message empty catch defect always. Failure-Mode-First error paths designed before happy path written catch before try validate inputs before any computation. Config validation typeof equals number AND range greater than 0 AND less than boundary before use throw descriptive error with field name expected range.`);

// === AS-T1-CORE ===
sections['AS-T1-CORE'] = padSection('T1 RUNTIME GRADE CORE', 
`7-Q: return Result Output or failure, error invalid input missing dep, side effect evidence log, callers all runtime functions, edge empty missing config, evidence op result hash, rollback error result caller handles. Build Order: Failure Mode First validate inputs, check deps typeof, error handlers before happy, implement P1-P10, collect evidence. P6 if typeof fs dot readFileSync not equals function throw Error P6 unavailable at module scope. P7 path join os dot homedir never hardcode home which breaks on macOS Windows CI containers. P4 acquire resource in try clear in finally guaranteed cleanup on both success and failure paths setInterval clearInterval open close connect disconnect. P3 log and propagate with timestamp module name message context return fallback matching output contract or re-throw enriched prepended to original. P10 success true data or success false error discriminated union accurate in ALL code paths including every error path never null never undefined never silent failure. Anti-patterns empty catch silently swallows errors creates undebuggable failures. Return null for object return type violates P10. Bare as any cast bypasses TypeScript type system without runtime guard violates P2.`);

// === AS-T1-FIREWALL ===
sections['AS-T1-FIREWALL'] = padSection('T1 FIREWALL', 
`7-Q: return findings file line, error program creation, side effect cache, callers pre-write audit, edge barrel d.ts, evidence file line severity, rollback discard program. Build Order: create Program, run 7 analyzers, aggregate findings, suppress dupes, report severity count, block critical. DeadExportDetector uses Program enumerate all exports checker dot findReferences check each excluding barrel index files intentionally re-exporting. SemanticFirewall pipeline CircularDependencyResolver traces imports detects cycles full path reporting. TypeCoverageAnalyzer measures non-any percentage per file flags below 0.95. APISurfaceAnalyzer enumerates exports with full type signatures detects accidental publics. ComplexityAnalyzer cyclomatic per function flags above 15 needs refactoring. DeadCodeEliminator findReferences unused exports excludes barrel index aggregation points. CodeGenValidator verifies patterns correct imports no eval no dynamic require non-literal. DependencyVersionAuditor CVE DB check per dep major mismatch direct vs transitive flagged. Each independent on same Program returning consistent file line severity message format. tsconfig strict noUncheckedIndexedAccess noImplicitReturns noUnusedLocals exactOptionalPropertyTypes. NEVER skipLibCheck false must verify external types.`);

// === AS-T1-NLP ===
sections['AS-T1-NLP'] = padSection('T1 NLP', 
`7-Q: return structured frame confidence, error unparseable zero matches, side effect parser state, callers intent router, edge empty multilingual, evidence frame confidence, rollback UNKNOWN. Build Order: buffer input, wink-nlp tokenise, PEG parse, verb-frame match, coref resolve, intent FSM route. Pipeline Raw to Tokeniser to Dep Parser to Verb-Frame to Intent FSM to Coref to Structured Frame. wink-nlp readDoc tokens each out normal isWord isPunctuation isNumber isEmail isURL span. PEG Peggy O-n deterministic zero backtracking. Streaming buffer ring flush delimiter or 5s. Coref LIFO gender number type. Intent FSM XState idle listening confirming collecting routing states transitions by verb-frame match events. Sentiment UP DOWN NEUTRAL 0-1 lexicon-based weighted keyword matching with negation handling. NER ENTITY_PATTERNS Map string to RegExp array for FILE_PATH COMMAND PACKAGE URL. Text Classification bag-of-concepts input vectors vs domain signatures. Language Detection n-gram frequency profiles against known language models. Spelling Levenshtein edit distance against known dictionary correction if within edit threshold. Temporal ISO 8601 date time normalize to standard UTC format. Template slot filling named parameters extracted from frame. All stages deterministic same input same output no model dependency. Pure rule-based pipeline compiled at build time from PEG grammar and verb-frame lexicon.`);

// === AS-T1-PERSISTENCE-TESTING ===
sections['AS-T1-PERSISTENCE-TESTING'] = padSection('T1 PERSISTENCE AND TESTING', 
`7-Q: return persistence result or test verdict, error SQLITE_BUSY or assertion fail, side effect evidence log writes, callers gates audit, edge concurrent writes container timeout, evidence Merkle integrity ContainerTestResult JSON, rollback transaction revert or container restart. Build Order: init SQLite WAL, event sourcing, write evidence, verify chain, container tests, collect results, advance gate. SQLite new Database path synchronous API WAL concurrent reads busy_timeout 5000 prevents lock contention errors. Event sourcing append DomainEvent type aggregateId timestamp data replay filter aggregateId call apply chronological snapshot every N events for fast recovery without full replay. Container 12-step docker run then cp bundle then SHA256 verify SRC vs DEST MUST MATCH exactly then install plugin then tmux create then launch opencode no-update then verify TUI poll Ask anything then send task two-step enter then wait result markers then collect evidence then teardown. Step 1 verify exit code 0 or FAIL stop do not proceed. Step 3 hash mismatch means copy corrupted DEPLOY FAILED redeploy. Step 7 poll stream.txt not tmux pane existence which can be bash.`);

// === AS-T1-STATE-CONCURRENCY ===
sections['AS-T1-STATE-CONCURRENCY'] = padSection('T1 STATE AND CONCURRENCY', 
`7-Q: return snapshot or error, error illegal transition or timeout, side effect transition log, callers actors supervisors, edge concurrent overload, evidence transition log SQLite Merkle, rollback checkpoint or circuit reset. Build Order: XState typed event union, pure guards, retry backoff, circuit breaker, token bucket, verify all paths. XState events discriminated union type field states idle loading active error recovery typed context per state. Guard registry Map string to GuardDefinition name severity pure predicate throw GuardError on violation with event type and expected constraint value describing exactly which precondition failed. Retry maxRetries 3 baseMs 1000 delay times pow 2 attempt plus random jitter 0-100ms prevents thundering herd synchronized retry storm. Token bucket max 60 refill 10 per second consume boolean false when empty caller must handle by rejecting or queuing not silently dropping. Circuit breaker threshold 5 failures within 60 second window reset 30000ms cooldown CLOSED to OPEN to HALF_OPEN allowing one probe request back to CLOSED on success or re-OPEN on failure.`);

// === STD-IDENTITY ===
sections['STD-IDENTITY'] = padSection('STD IDENTITY BIBLE', 
`7-Q: return injected identity block, error missing markers, side effect prompt modification, callers transform compaction, edge multi-agent toggle competition, evidence identity markers START END, rollback remove re-inject. Build Order: detect session Map ID, load identity registry, SCAN+REPLACE system messages IDENTITY_BLOCK_START END, validate markers present, log event timestamp. 9-canon document system TRIDENT.md core identity binding name version role purpose. IDENTITY.md response rules identity answers who what are you questions. EXECUTION.md 3-step SELECT EXECUTE PRESENT flow all tool interactions. QUALITY.md evidence gates theatrical detection Merkle verification integrity proof. TOOLS.md tool registry schemas blocked lists per agent. AGENT_AWARENESS.md self-knowledge limitations capabilities documentation. FIREWALL_CONTEXT.md blocked tools zone protection rules per phase. explore-protocol.md trident_explore dispatch system V1 V2 formats. POST_COMPACTION_PROMPT.md recovery instructions after memory clearing. Each canon distinct non-overlapping aspect collectively complete specification. Tab-toggle Map string AgentState session keyed switch replaces via system.transform SCAN+REPLACE between markers replaces content. If markers absent append once at top of system messages never append twice causing duplication.`);

// === STD-AGENT-ARCHITECTURE ===
sections['STD-AGENT-ARCHITECTURE'] = padSection('STD AGENT ARCHITECTURE', 
`7-Q: return state capabilities, error unregistered session, side effect tool execution evidence, callers orchestrator user, edge multi-agent tool contention, evidence execution log timestamps, rollback last checkpoint. Build Order: init identity tools, register session Map, handle lifecycle events, collect evidence, advance gates. Maturity Spectrum L1 single-agent hand-crafted prompts no tool integration no memory no hooks. L2 multi-agent tool-based specialization each agent distinct tools identity operational scope. L3 agentic dynamic task decomposition spawn sub-agents for complex tasks collect results structured communication channels. L4 autonomous self-improvement loops analyze own execution performance automatically update prompts and tools to improve. Trident operates at L3 with structured audit layers R0 through R16 providing deterministic code review capability. Prompt architecture four structural sections Role identity capabilities constraints binding. Tool list all registered tools with JSON schemas parameter descriptions allow block status per agent. Rules MUST MUST NOT directives enforced by hook-level checks not just prompt instructions. Knowledge T1 sections synthesized from knowledge library injected every system.transform for fresh context. Structured output enforcement all tool returns typed JSON validated zod schemas before return.`);

// === STD-COMMON-SENSE ===
sections['STD-COMMON-SENSE'] = padSection('STD COMMON SENSE', 
`7-Q: return verified conclusion, error insufficient evidence, side effect audit log, callers audit gates, edge circular fabricated evidence, evidence filesystem proof hash timestamp, rollback invalidate tainted chain. Build Order: state claim, identify evidence, locate filesystem, verify hash timestamp, cross-reference, reject unverifiable. Law 1 all claims filesystem proof exit codes output diffs timestamps prose not evidence. Law 2 pre-write enforcement prevents before filesystem lock prevents camera detects after damage done. Law 3 measure outcomes exit codes not confidence percentages which carry zero evidentiary weight. Law 4 never optimize unmeasured benchmark both before and after any change. Law 5 delete dead code before adding new features deletion zero regression risk reduces maintenance. Law 6 best code unwritten zero bugs zero maintenance zero cognitive load. Law 7 theatrical code worse than wrong code false confidence prevents debugging empty catches always-true guards stub assert nothing more dangerous than obviously broken code which gets fixed. Law 8 one source per invariant delete all duplication. Law 9 verify at defect proximity late detection multiplies remediation cost exponentially with distance from origin. Law 10 no silent failures crash visible debuggable silent corruption spreads undetected. Law 11 context contract modules document needs provides assumes explicitly. Law 12 output IS work documentation evidence artifacts deliverables equal value to source code. Theatrical Matrix Return O5 Check O5 ErrorHandler O2 HIGH Test O5 Config O5 Type O3 Import O3. Only O5 reliable introduce bug verify test fails.`);

// === STD-SEMANTIC-ENGINEERING ===
sections['STD-SEMANTIC-ENGINEERING'] = padSection('STD SEMANTIC ENGINEERING', 
`7-Q: return analysis verdict, error missing types, side effect compiler cache, callers audit pre-write, edge d.ts dynamic imports, evidence O0-O4 findings per order, rollback discard program. Build Order: identify order per check, create compiler structures, execute analysis, collect evidence, cross-reference orders. Five Orders of Program Analysis detailed O0 regex candidate only NEVER final verdict because regex cannot distinguish source code from identical text appearing in comments or string literals fundamental limitation. O1 token lexical structure token types sequences. O2 AST parse tree SyntaxKind node types structural invariants unambiguous zero false positives from code-in-comments because tree verified by compiler. O3 TypeChecker getTypeAtLocation getSymbolAtLocation getResolvedSignature catches what AST misses as any type system bypass function overload resolution ambiguity structural type compatibility violations. O4 CFG DFA getControlFlowGraph data flow analysis Error Path Audit traces every code path from function entry through every error-producing operation to every corresponding error handler. Code path with zero handlers for error-producing operation equals defect regardless of whether other paths properly handled. Each Order has specific tools and evidence format. Lower Order cannot perform higher Order semantic analysis. SPEC property testing formal specifications.`);

// === STD-AUDIT-PLAN ===
sections['STD-AUDIT-PLAN'] = padSection('STD AUDIT AND PLAN', 
`7-Q: return audit report or plan artifact, error missing evidence contradictory, side effect gate update evidence write, callers gates human reviewers, edge incomplete sources conflicting findings, evidence audit md file, rollback revert gate state SQLite. Build Order: pre-flight verify sources, audit layer-by-layer R0-R16 file:line evidence, classify severity, produce artifact, block if critical. Two deliverables AUDIT finds problems describes impact PLAN describes fixes ordered by dependency. Pre-flight verification verify file paths exist filesystem. Dry-run tool schemas required params provided. Check gate state only DELIVERY allows deploy. SHA256 source matches last deployed bundle mismatch means unstaged changes must commit first. Confirm session write permissions for target scope check session agent allowlist has access. AUDIT R0-R16 layer analysis each finding file path line number severity CRITICAL blocks gate HIGH requires fix before merge MEDIUM should fix LOW nice to have INFO observation. Confidence score 0.0-1.0 per finding. Reproduction command per finding so human can independently verify. PLAN phased implementation exact code changes per file dependency order between phases verification commands per phase lint typecheck test.`);

// === TILE-SPAWN-SHARK ===
sections['TILE-SPAWN-SHARK'] = padSection('SHARK TILE SPAWN', 
`7-Q: return tile ID verified position, error canvas full IPC fail, side effect new terminal tile, callers VLM spawn orchestrator, edge overlap bash not prompt, evidence tileList position verify, rollback tileRemove. Build Order: verify container IPC, VLM capture CDP 9223, calculate grid, canvas.tileCreate tileType term x y w h, canvas.terminalWrite input param, verify TUI poll Ask anything, verify tileList position matches request. Verified working coordinates x 320 y 4080 row 5 canvas standard size 920 by 1000. CRITICAL FORBIDDEN session.create pty-sidecar orphan PTY no tile visible. type terminal broken note tile use tileType term. data param silent noop only input works. tileCreate without position hidden off-screen invisible not reachable. Correct procedure canvas.tileCreate name tileType term position x y size w h. canvas.terminalWrite param input shell command string. tmux send-keys text then 1 second delay then Enter as SEPARATE key sequence never combined text backslash n which TUI interprets as literal characters. Verify stream.txt expected output text. Ask anything string is definitive TUI loaded indicator. Always set OPENCODE_SKIP_UPDATE equals 1 environment variable before launch to disable auto-update that breaks running instance. Permissions opencode.json root level star colon star colon allow not agent-level overridden.`);

// ================================================================
// GENERATE OUTPUT
// ================================================================
const keys = Object.keys(sections);
const maxKeyLength = Math.max(...keys.map(k => k.length));

console.log(`/**
 * PRE-SYNTHESIZED T1 KNOWLEDGE — Each section EXACTLY ${TARGET_TOKENS} tokens (${TARGET_CHARS} chars).
 * Token count = Math.ceil(chars / 4). Verify via getPreSynthesizedT1TokenCount().
 * Generated: ${new Date().toISOString().split('T')[0]}. Sources: 36 sections (9 KB + 7 CS + 15 AS + 6 STD)
 * Each section verified at exactly ${TARGET_TOKENS} tokens.
 */

export const PRE_SYNTHESIZED_T1: Record<string, string> = {`);

for (const key of keys) {
  const content = sections[key];
  const tokens = Math.ceil(content.length / 4);
  console.log(`  '${key}': ${content},`);
}

console.log(`};

/**
 * Returns the total token count estimate for all pre-synthesized T1 sections.
 */
export function getPreSynthesizedT1TokenCount(): number {
  let totalChars = 0;
  for (const value of Object.values(PRE_SYNTHESIZED_T1)) {
    totalChars += value.length;
  }
  return Math.ceil(totalChars / 4);
}

/**
 * Returns all pre-synthesized T1 sections joined as a single string.
 */
export function getPreSynthesizedT1String(): string {
  return Object.values(PRE_SYNTHESIZED_T1).join('\\n\\n');
}
`);

// Verify all sections
console.error('\n=== VERIFICATION ===');
let allOk = true;
for (const [key, content] of Object.entries(sections)) {
  const chars = content.length;
  const tokens = Math.ceil(chars / 4);
  const status = tokens === TARGET_TOKENS ? 'OK' : 'FAIL';
  if (status !== 'OK') {
    console.error(`${status} ${key}: ${tokens}t (${chars}c)`);
    allOk = false;
  }
}
if (allOk) {
  console.error(`All ${Object.keys(sections).length} sections: EXACTLY ${TARGET_TOKENS} tokens each ✓`);
} else {
  console.error('Some sections FAILED token count check');
  process.exit(1);
}
